version: '3'
services:
  app:
    build: .
    env_file: .env-test
    command: ["dev"]
    links:
      - postgres:postgres
    restart: always
    labels:
      - traefik.enable=false
    ports:
      - 9009:9009
  postgres:
    image: postgres
    container_name: covid_postgres_test
    env_file: .env-test
    restart: always
    labels:
      - traefik.enable=false
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
volumes:
  postgresdata:

