version: '3'
services:
  app:
    build: .
    volumes:
      - ./src:/usr/src/app
    env_file: .env-prod
    command: ["prod"]
    networks:
      - internal
    links:
      - postgres:postgres
    labels:
      - traefik.enable=false
    restart: always
  postgres:
    image: postgres
    env_file: .env-prod
    networks:
      - internal
    restart: always
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    labels:
      - traefik.enable=false
  nginx:
    build:
      context: nginx/
      dockerfile: Dockerfile.nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.webcagnoting.rule=Host(`cagnoting-be.zifendel.com`)"
      - "traefik.http.routers.webcagnotingmi.entrypoints=websecure"
      - "traefik.http.routers.webcagnoting.tls.certresolver=myresolver"
      - "traefik.docker.network=proxy"
      - "traefik.port=80"
    networks:
      - internal
      - proxy
    links:
      - app:web
    depends_on:
        - app
    restart: always
volumes:
  dbdata:
networks:
  proxy:
    external: true
  internal:
    external: false
